baseurl = "https://antopolskiy.github.io"
title = "My blog"
languageCode = "en-us"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Calin Tataru"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:s.antopolsky@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/antopolskiy/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/antopolskiy/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/antop/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/3033945/sergey-antopolskiy"
    name = "fab fa-stack-overflow"
    weight = 5
