baseurl = "https://antopolskiy.github.io"
title = "Home"
languageCode = "en-us"
theme = "minimal"
disqusShortname = "https-antopolskiy-github-io" # delete this to disable disqus comments

[params]
    author = "Sergey Antopolskiy"
    description = "Hi there! My name is Sergey Antopolskiy, I am technical lead @ [Mosaiq Labs](https://mosaiqlabs.com) and here I write about things related to data science, AI, cloud services, devops and tangential topics."
    githubUsername = "antopolskiy"
    accent = "#9c27b0"
    showBorder = true
    backgroundColor = "white"
    font = "Source Sans Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "json", "bash", "yaml", "toml", "go", "java", "javascript", "html", "css", "sql", "r", "cpp", "c", "dockerfile", "makefile", "nginx", "shell", "swift", "typescript", "xml", "kotlin", "rust", "powershell", "ruby", "scala", "haskell", "perl", "lua", "matlab", "scheme", "clojure", "erlang", "elixir", "fortran", "lisp", "pascal", "prolog", "vhdl", "verilog", "coffeescript", "diff", "django", "jinja", "latex", "markdown", "nginx", "nginxconf", "protobuf", "toml", "vim", "x86asm", "yaml"]
    #profilePic = "toptal_profile_pic.jpeg"
    #font_size = "20"
    #custom_css = ["static/main.css"]
    #copyright = " "
    
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github'
    tabWidth = 4

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

#[[menu.main]]
#    url = "/about/"
#    name = "About"
#    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:s.antopolsky@gmail.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/antopolskiy/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/antopolskiy/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/antop/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/3033945/sergey-antopolskiy"
    name = "fab fa-stack-overflow"
    weight = 5
